### ISSUE TITLE
Android crashing again..?

### ISSUE THREAD

**Issue by Link-Jon** [MCJack123/craftos2#372]
I am unsure if its simply [issue 254](https://github.com/MCJack123/craftos2/issues/254#issue-1284716869) again, but I myself and apparently two others are crashing on launch.

Note, this data is just using the google play store reviews, and so may or may not be fully correct. (Even my own devices are partially from memory.)

The devices that have been seen to crash on launch are:
_Moto G Stylus 5g 2024 // XT2419V (Android 14)_ --Had to double check. Thought it was 13... Actually 14.
_Google Pixel 8 (Android 14)_
_Device OnePlus 9 Pro? (OxygenOS14 AKA Android 14)_

However, there's also known devices where it simply works.
_Moto G Stylus 2020 (Android 12..?)_
_Device OnePlus 9 Pro (OxygenOS13 AKA Android 13)_

With my very very limited data, i think something CraftOS is relying on was removed between android 13 and 14.
However, I myself dont know enough about the project to actually know what.

**Comment by MCJack123** [comment]
Looks like Android 14 changed some stuff with requesting USB permissions which is causing this crash. The problem is from upstream SDL, and was fixed in https://github.com/libsdl-org/SDL/commit/5a26b26880539e4c54e8457290a8586a0a086ca8 - I'll have to merge the latest code into my project to fix this.

**Comment by Racooder** [comment]
On my device (Samsung Galaxy A25 / Android 14) it also crashes on startup. Hope that helps.

**Comment by QM8782** [comment]
I still see it crash as well. No matter if I open it, it crashes instantly after. This is confirmed from other users and me.

PS: My device is the Samsung Galaxy A14.

**Comment by Redd56** [comment]
Using a galaxy flip 5 same issue

**Comment by trainzkid** [comment]
Same on the OnePlus 13

**Comment by LipeAma** [comment]
same on motorola edge 60 pro

**Comment by MCJack123** [comment]
I have been aware of the issue, but haven't had the opportunity to push a full update - there's a number of backend tasks I need to complete first which are a major time drain for me. In the meantime, here is a temporary APK that should fix the issue. Note that this may not play well with past or future updates, so be careful using it.

https://files.catbox.moe/ych10r.apk
