### ISSUE TITLE
config.get("readFail") returns not real nil

### ISSUE THREAD

**Issue by Le0Developer** [MCJack123/craftos2#57]
Executing `config list` will only show the first half of all available options because it errores, midway through.

```lua
> config list
http_enable = true
debug_enable = false
disable_lua51_features = false
default_computer_settings = 
logPeripheralErrors = false
computerSpaceLimit = 1000000
maximumFilesOpen = 128
maxNotesPerTick = 8
clockSpeed = 20
showFPS = false
[string "config.lua"]:6: bad argument #1 to ´tostring´ (value expected)
```

Problem
---
`config.get("readFail")` returns not real nil.

`config.get("readFail") == nil` is true, but

`tostring(nil)`, returns "nil"
`tostring(config.get("readFail"))`, errors

Pseudo Fix
---
This fixes `config.lua` to avoid calling `tostring()` with a nil value.

Just check if it's nil or not.
```lua
local args = { ... }

if args[1] == "list" then
    local settings = config.list()
    for k,v in pairs(settings) do
        -- is it not nil?
        if config.get( v ) ~= nil then
          print(v .. " = " .. tostring(config.get(v)))
        else
          print(v .. " = nil")
        end
    end
elseif args[1] == "get" and args[2] ~= nil then
    local setting = config.get(args[2])
    if setting == nil then error("Unknown setting " .. args[2])
    else print(tostring(setting)) end
elseif args[1] == "set" and args[3] ~= nil then
    local type = config.getType(args[2])
    if type == 0 then config.set(args[2], args[3] == "true" or args[3] == "1")
    elseif type == 1 then config.set(args[2], args[3])
    elseif type == 2 then config.set(args[2], tonumber(args[3]))
    else error("Unknown setting " .. args[2]) end
else
    term.setTextColor(colors.red)
    print("Usage: config <get|set|list> [setting] [value]")
    term.setTextColor(colors.white)
end
```

I'd have created a pull request, but I didn't find `rom` on the github.

**Comment by MCJack123** [comment]
Just found this on my own yesterday. It's fixed in the latest commit to the [ROM](https://github.com/MCJack123/craftos2-rom).

**Comment by Le0Developer** [comment]
The issue still exists.
```lua
lua> tostring( config.get("does_not_exists") )
[string "lua"]:1: bad argument #1 to ´tostring´ (value expected)
lua> config.get("does_not_exists") == nil
true
```
config.get() does **not** return real nil

**Comment by MCJack123** [comment]
Turns out I was looking at a different issue, it's actually fixed in the latest commit.
